/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4vA3yB1zSDX
 */
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

export function FakeComp() {
  return (
    <form className="space-y-4">
      <Input className="w-full" placeholder="Restaurant Name" type="text" />
      <Input className="w-full" placeholder="Location" type="text" />
      <div className="space-y-4">
        <Label className="text-base" htmlFor="dishes">
          Dishes
        </Label>
        <div id="dishes">
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Input className="w-full" placeholder="Dish Name" type="text" />
              <Input className="w-full" placeholder="Rating" type="text" />
            </div>
            <div className="grid gap-2">
              <Input className="w-full" placeholder="Dish Name" type="text" />
              <Input className="w-full" placeholder="Rating" type="text" />
            </div>
            <div className="grid gap-2">
              <Input className="w-full" placeholder="Dish Name" type="text" />
              <Input className="w-full" placeholder="Rating" type="text" />
            </div>
          </div>
        </div>
      </div>
      <Input className="w-full" placeholder="Overall Rating" type="text" />
      <div className="flex items-center space-x-4">
        <Label className="text-base" htmlFor="visitAgain">
          Would visit again?
        </Label>
        <div className="flex items-center space-x-2" id="visitAgain">
          <input className="form-radio" id="yes" name="visitAgain" type="radio" value="yes" />
          <label className="text-base" htmlFor="yes">
            Yes
          </label>
          <input className="form-radio" id="no" name="visitAgain" type="radio" value="no" />
          <label className="text-base" htmlFor="no">
            No
          </label>
        </div>
      </div>
      <Button className="btn btn-primary w-full" type="submit">
        Add Restaurant
      </Button>
    </form>
  )
}
